cors:
  originPatterns: http://localhost:3000, http://localhost:8080
file:
  upload-dir: /home/runner/work/rest-with-spring-boot-and-kotlin-erudio/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rest-with-springboot-erudio-edwin-lima.c7bwceqgsysk.us-east-1.rds.amazonaws.com:3306/rest-with-springboot-erudio-edwin-lima?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin123
#    url: jdbc:mysql://localhost:3306/rest_with_springboot_erudio?useTimezone=true&serverTimezone=UTC
#    username: root
#    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true